tfn.resources = [
	{ id: "background", src: "data/img/background.png" },
	{ id: "background-title", src: "data/img/background-title.png" },
	{ id: "background-blank", src: "data/img/background-blank.png" },
	{ id: "menu-button-credits", src: "data/img/menu-button-credits.png" },
	{ id: "menu-button-new-game", src: "data/img/menu-button-new-game.png" },
	{ id: "menu-button-options", src: "data/img/menu-button-options.png" },
	{ id: "menu-button-tutorial", src: "data/img/menu-button-tutorial.png" },
	{ id: "menu-button-create-game", src: "data/img/menu-button-create-game.png" },
	{ id: "menu-button-join-game", src: "data/img/menu-button-join-game.png" },
	{ id: "menu-button-exit-lobby", src: "data/img/menu-button-exit-lobby.png" },
	{ id: "menu-button-start-game", src: "data/img/menu-button-start-game.png" },
	{ id: "menu-label-waiting", src: "data/img/menu-label-waiting.png" },
	{ id: "menu-button-ready", src: "data/img/menu-button-ready.png" },
	{ id: "menu-image-instructions", src: "data/img/menu-image-instructions.png" },
	{ id: "map-blue", src: "data/img/map-blue.png" },
	
	// Tanks
	{ id: "tank-body-red", src: "data/img/tank-body-red.png" },
	{ id: "tank-body-green", src: "data/img/tank-body-green.png" },
	{ id: "tank-body-orange", src: "data/img/tank-body-orange.png" },
	{ id: "tank-body-yellow", src: "data/img/tank-body-yellow.png" },	
	{ id: "tank-turret-red", src: "data/img/tank-turret-red.png" },
	{ id: "tank-turret-green", src: "data/img/tank-turret-green.png" },
	{ id: "tank-turret-orange", src: "data/img/tank-turret-orange.png" },
	{ id: "tank-turret-yellow", src: "data/img/tank-turret-yellow.png" },
	{ id: "tank-bullet-red", src: "data/img/tank-bullet-red.png" },
	{ id: "tank-bullet-green", src: "data/img/tank-bullet-green.png" },
	{ id: "tank-bullet-orange", src: "data/img/tank-bullet-orange.png" },
	{ id: "tank-bullet-yellow", src: "data/img/tank-bullet-yellow.png" },
];
