tfn.resources = [
	{ id: "background", src: "data/img/sliced/background.png" },
	{ id: "background-title", src: "data/img/sliced/background-title.png" },
	{ id: "background-blank", src: "data/img/sliced/background-blank.png" },
	{ id: "menu-button-credits", src: "data/img/sliced/menu-button-credits.png" },
	{ id: "menu-button-new-game", src: "data/img/sliced/menu-button-new-game.png" },
	{ id: "menu-button-options", src: "data/img/sliced/menu-button-options.png" },
	{ id: "menu-button-tutorial", src: "data/img/sliced/menu-button-tutorial.png" },
	{ id: "menu-button-create-game", src: "data/img/sliced/menu-button-create-game.png" },
	{ id: "menu-button-join-game", src: "data/img/sliced/menu-button-join-game.png" },
	{ id: "menu-button-exit-lobby", src: "data/img/sliced/menu-button-exit-lobby.png" },
	{ id: "menu-button-start-game", src: "data/img/sliced/menu-button-start-game.png" },
	{ id: "menu-label-waiting", src: "data/img/sliced/menu-label-waiting.png" },
	{ id: "menu-button-ready", src: "data/img/sliced/menu-button-ready.png" },
	{ id: "menu-image-instructions", src: "data/img/sliced/menu-image-instructions.png" },
	{ id: "tank-body-red", src: "data/img/sliced/tank-body-red.png" },
	{ id: "tank-turret-red", src: "data/img/sliced/tank-turret-red.png" },
	{ id: "map-blue", src: "data/img/sliced/map-blue.png" },
];
